title: Kijin Seong, PhD, AICP
logo: "/asset/img/KijinSeong_headshot_sq.jpg?raw=true"
description: 
  <p align="center">
  Austin, TX, USA
  <br> kijin.seong@austin.utexas.edu
  <br> <a href="XXXXXXXXX.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/kijin-seong-phd-aicp-5833417b/">LinkedIn</a> |
  <a href="https://github.com/kijinseong/">GitHub</a> 
  <br> <a href="https://www.researchgate.net/profile/Kijin-Seong">ResearchGate</a> |
  <a href="https://scholar.google.com/citations?user=GcRv_SUAAAAJ&hl=en&oi=ao">GoogleScholar</a> |
  </p>

  <p align="justify">
  Hi! I am <b>Kijin Seong<b>, and I am a postdoctoral researcher at the Urban Information Lab in the School of Architecture at the University of Texas at Austin.
  <br><br>
  My research centers on leveraging <b>urban informatics and emerging technologies<b> to enhance the <b>climate resilience<b> of smart cities. 
  <br><br>
  I am passionate about using data-driven approaches to improve urban planning and address environmental challenges, and I continually seek opportunities to expand my expertise in this field. 
  <br><br>
  </p>



show_downloads: true
theme: jekyll-theme-minimal

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
